<?php
/**
 * @author Amit Samsukha <amit@emizentech.com>
 */
?>
<?php
$stores  = $this->getAllStores();
?>
<?php foreach($stores as $_store):?>
		<?php //var_dump($_store->debug());?>
		<?php $lt = $_store->getLatitude();?>
		<?php $lg = $_store->getLongitude();?>
<?php endforeach;?>

    
    
	<script src="http://maps.google.com/maps/api/js" ></script>
    <script >
    var map;
    var markers = [];
    var infoWindow;
    var locationSelect;

    function init() {
      map = new google.maps.Map(document.getElementById("map"), {
        center: new google.maps.LatLng(<?php echo $lt?>, <?php echo $lg?>),
        zoom: 10,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
         mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU}
      });
      infoWindow = new google.maps.InfoWindow();

      locationSelect = document.getElementById("locationSelect");
      locationSelect.onchange = function() {
        var markerNum = locationSelect.options[locationSelect.selectedIndex].value;
        if (markerNum != "none"){
          google.maps.event.trigger(markers[markerNum], 'click');
        }
      };
      searchLocationsNear(new google.maps.LatLng(<?php echo $lt?>, <?php echo $lg?>));
   }

   function searchLocations() {
     var address = document.getElementById("addressInput").value;
     var geocoder = new google.maps.Geocoder();
     geocoder.geocode({address: address}, function(results, status) {
       if (status == google.maps.GeocoderStatus.OK) {
        searchLocationsNear(results[0].geometry.location);
       } else {
         alert(address + ' not found');
       }
     });
   }

   function clearLocations() {
     infoWindow.close();
     for (var i = 0; i < markers.length; i++) {
       markers[i].setMap(null);
     }
     markers.length = 0;

     locationSelect.innerHTML = "";
     var option = document.createElement("option");
     option.value = "none";
     option.innerHTML = "Select Store:";
     locationSelect.appendChild(option);
   }
   
   function searchLocationsNear(center) {
     clearLocations(); 

     var radius = document.getElementById('radiusSelect').value;
     var searchUrl = '<?php echo $this->getUrl('storelocator/index/search');?>?lat=' + center.lat() + '&lng=' + center.lng() + '&radius=' + radius;
     downloadUrl(searchUrl, function(data) {
       var xml = parseXml(data);
       var markerNodes = xml.documentElement.getElementsByTagName("marker");
       var bounds = new google.maps.LatLngBounds();
       for (var i = 0; i < markerNodes.length; i++) {
         var name = markerNodes[i].getAttribute("name");
         var address = markerNodes[i].getAttribute("address");
         var distance = parseFloat(markerNodes[i].getAttribute("distance"));
         var latlng = new google.maps.LatLng(
              parseFloat(markerNodes[i].getAttribute("lat")),
              parseFloat(markerNodes[i].getAttribute("lng")));

         createOption(name, distance, i);
         createMarker(latlng, name, address);
         bounds.extend(latlng);
       }
       map.fitBounds(bounds);
       locationSelect.style.visibility = "visible";
       locationSelect.onchange = function() {
         var markerNum = locationSelect.options[locationSelect.selectedIndex].value;
         google.maps.event.trigger(markers[markerNum], 'click');
       };
      });
    }
  
    function createMarker(latlng, name, address) {
      var html = "<b>" + name + "</b> <br/>" + address;
      var marker = new google.maps.Marker({
        map: map,
        position: latlng
      });
      google.maps.event.addListener(marker, 'click', function() {
        infoWindow.setContent(html);
        infoWindow.open(map, marker);
      });
      markers.push(marker);
    }

    function createOption(name, distance, num) {
      var option = document.createElement("option");
      option.value = num;
      option.innerHTML = name + "(" + distance.toFixed(1) + ")";
      locationSelect.appendChild(option);
    }

    function downloadUrl(url, callback) {
      var request = window.ActiveXObject ?
          new ActiveXObject('Microsoft.XMLHTTP') :
          new XMLHttpRequest;

      request.onreadystatechange = function() {
        if (request.readyState == 4) {
          request.onreadystatechange = doNothing;
          callback(request.responseText, request.status);
        }
      };

      request.open('GET', url, true);
      request.send(null);
    }

    function parseXml(str) {
      if (window.ActiveXObject) {
        var doc = new ActiveXObject('Microsoft.XMLDOM');
        doc.loadXML(str);
        return doc;
      } else if (window.DOMParser) {
        return (new DOMParser).parseFromString(str, 'text/xml');
      }
    }
	
	function doNothing(){}
	
	google.maps.event.addDomListener(window, 'load', init);
	

  </script>
    <div class="field">
    <div class="control">
     <input type="text" class="input-text" id="addressInput" placeholder="Enter a Location to Search"/>
		<select id="radiusSelect" class="input-select">
			<option value="" >Select Distance</option>
		  	<option value="25" selected>25mi</option>
		  	<option value="100">100mi</option>
		  	<option value="200">200mi</option>
		</select>
    	<button type="submit" onclick="searchLocations()" class="action submit primary">Search</button>
    </div>
    </div>
    <strong>Select Store Location(s):</strong>
    <div>
    	<select id="locationSelect" style="width:100%;visibility:hidden">
    	</select>
    </div>
    <div style="clear:both;"></div>
    <div id="map" class="store-map" style="width: 100%; height: 80%"></div>